-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, (p.PRICE * SUM(os.SALES_AMOUNT)) AS SALES
FROM PRODUCT p LEFT JOIN OFFLINE_SALE os
    ON p.PRODUCT_ID = os.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE ASC;