WITH TBL AS (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES,
    MAX(FAVORITES) OVER (PARTITION BY FOOD_TYPE) AS MAX_FAVORITES
    FROM REST_INFO
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM TBL
WHERE FAVORITES = MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;