-- 코드를 입력하세요
SELECT gu.USER_ID, gu.NICKNAME, SUM(gb.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD gb LEFT JOIN USED_GOODS_USER gu
    ON gb.WRITER_ID = gu.USER_ID
WHERE gb.STATUS LIKE 'DONE'
GROUP BY gb.WRITER_ID
HAVING SUM(gb.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;