-- 코드를 입력하세요
SELECT DISTINCT(c.CAR_ID) AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY rh
    ON c.CAR_ID = rh.CAR_ID
WHERE c.CAR_TYPE LIKE '세단' AND DATE_FORMAT(rh.START_DATE, '%Y-%m') = '2022-10'
ORDER BY c.CAR_ID DESC;