-- 코드를 작성해주세요
WITH TEMP AS(
SELECT SUM(g.SCORE) AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM HR_EMPLOYEES e JOIN HR_GRADE g
    ON e.EMP_NO = g.EMP_NO
WHERE g.YEAR = 2022
GROUP BY e.EMP_NO
)


SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM TEMP
WHERE SCORE = (
SELECT MAX(SCORE)
FROM TEMP
);