-- 코드를 입력하세요
SELECT b.CATEGORY as CATEGORY, SUM(bs.SALES) as TOTAL_SALES
FROM BOOK b LEFT JOIN BOOK_SALES bs
    ON b.BOOK_ID = bs.BOOK_ID
WHERE bs.SALES_DATE Like '2022-01%'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;